export type GeoLigne = {
  labels: [string, string];
  mots_1: string[];
  term_1: string[];
  mots_2: string[];
  term_2: string[];
};

export const GEOGRAPHIE_RER: Record<string, GeoLigne> = {
  A: {
    labels: ['⇦ OUEST (Cergy / Poissy / St-Germain)', '⇨ EST (Marne-la-Vallée / Boissy)'],
    mots_1: ['CERGY','POISSY','GERMAIN','RUEIL','DEFENSE','DÉFENSE','NANTERRE','VESINET','MAISONS','LAFFITTE','PECQ','ACHERES','GRANDE ARCHE','SARTROUVILLE'],
    term_1: ['HAUT','POISSY','GERMAIN'],
    mots_2: ['MARNE','BOISSY','TORCY','NATION','VINCENNES','FONTENAY','NOISY','JOINVILLE','VALLEE','CHESSY','DISNEY'],
    term_2: ['CHESSY','BOISSY'],
  },
  B: {
    labels: ['⇩ SUD (St-Rémy / Robinson)', '⇧ NORD (Roissy / Mitry)'],
    mots_1: ['REMY','RÉMY','ROBINSON','LAPLACE','DENFERT','CITE','MASSY','ORSAY','BOURG','CROIX','GENTILLY','ARCUEIL','BAGNEUX'],
    term_1: ['REMY','RÉMY','ROBINSON'],
    mots_2: ['GAULLE','MITRY','NORD','AULNAY','BOURGET','LA PLAINE','CLAYE','AÉROPORT'],
    term_2: ['GAULLE','MITRY'],
  },
  C: {
    labels: ['⇦ OUEST (Versailles / Pontoise)', '⇨ SUD/EST (Massy / Dourdan / Étampes)'],
    mots_1: ['INVALIDES','AUSTERLITZ','VERSAILLES','QUENTIN','PONTOISE','CHAMP','EIFFEL','CHAVILLE','ERMONT','JAVEL','ALMA','VELIZY','BEAUCHAMP','MONTIGNY','ARGENTEUIL'],
    term_1: ['VERSAILLES','QUENTIN','PONTOISE','AUSTERLITZ'],
    mots_2: ['MASSY','DOURDAN','ETAMPES','ÉTAMPES','MARTIN','JUVISY','BIBLIOTHEQUE','ORLY','RUNGIS','BRETIGNY','BRÉTIGNY','CHOISY','IVRY','ATHIS','SAVIGNY'],
    term_2: ['DOURDAN','ETAMPES','ÉTAMPES','MASSY','BRÉTIGNY'],
  },
  D: {
    labels: ['⇩ SUD (Melun / Corbeil)', '⇧ NORD (Creil)'],
    mots_1: ['MELUN','CORBEIL','MALESHERBES','VILLENEUVE','COMBS','FERTE','LIEUSAINT','JUVISY'],
    term_1: ['MELUN','CORBEIL','MALESHERBES'],
    mots_2: ['CREIL','GOUSSAINVILLE','ORRY','VILLIERS','STADE','DENIS','LOUVRES','SURVILLIERS','GARE DE LYON','PARIS','CHATELET','NORD'],
    term_2: ['CREIL','ORRY','GOUSSAINVILLE'],
  },
  E: {
    labels: ['⇦ OUEST (Nanterre)', '⇨ EST (Chelles / Tournan)'],
    mots_1: ['HAUSSMANN','LAZARE','MAGENTA','NANTERRE','DEFENSE','DÉFENSE','ROSA'],
    term_1: ['NANTERRE','HAUSSMANN'],
    mots_2: ['CHELLES','TOURNAN','VILLIERS','GAGNY','EMERAINVILLE','ROISSY','NOISY','BONDY'],
    term_2: ['CHELLES','TOURNAN'],
  },
  H: {
    labels: ['⇧ NORD (Pontoise / Persan / Creil)', '⇩ PARIS NORD'],
    mots_1: ['PONTOISE','PERSAN','BEAUMONT','LUZARCHES','CREIL','MONTSOULT','VALMONDOIS','SAINT-LEU','SARCELLES','BRICE'],
    term_1: ['PONTOISE','PERSAN','LUZARCHES','CREIL'],
    mots_2: ['PARIS','NORD'],
    term_2: ['PARIS','NORD'],
  },
  J: {
    labels: ['⇦ OUEST (Mantes / Gisors / Ermont)', '⇨ PARIS ST-LAZARE'],
    mots_1: ['MANTES','JOLIE','GISORS','ERMONT','VERNON','PONTOISE','CONFLANS','BOISSY','MEULAN','MUREAUX','CORMEILLES','ARGENTEUIL','ISSOU'],
    term_1: ['MANTES','GISORS','ERMONT','VERNON'],
    mots_2: ['PARIS','LAZARE'],
    term_2: ['PARIS','LAZARE'],
  },
  K: {
    labels: ['⇧ NORD (Crépy-en-Valois)', '⇩ PARIS NORD'],
    mots_1: ['CREPY','CRÉPY','DAMMARTIN'],
    term_1: ['CREPY','CRÉPY'],
    mots_2: ['PARIS','NORD'],
    term_2: ['PARIS','NORD'],
  },
  L: {
    labels: ['⇦ OUEST (Versailles / St-Nom / Cergy)', '⇨ PARIS ST-LAZARE'],
    mots_1: ['VERSAILLES','NOM','BRETÈCHE','CERGY','NANTERRE','MAISONS','CLOUD','SARTROUVILLE'],
    term_1: ['VERSAILLES','NOM','HAUT'],
    mots_2: ['PARIS','LAZARE'],
    term_2: ['PARIS','LAZARE'],
  },
  N: {
    labels: ['⇦ OUEST (Rambouillet / Dreux / Mantes)', '⇨ PARIS MONTPARNASSE'],
    mots_1: ['RAMBOUILLET','DREUX','MANTES','JOLIE','PLAISIR','SEVRES','SÈVRES'],
    term_1: ['RAMBOUILLET','DREUX','MANTES'],
    mots_2: ['PARIS','MONTPARNASSE'],
    term_2: ['PARIS','MONTPARNASSE'],
  },
  P: {
    labels: ['⇨ EST (Meaux / Provins / Coulommiers)', '⇦ PARIS EST'],
    mots_1: ['MEAUX','CHATEAU','CHÂTEAU','THIERRY','FERTE','FERTÉ','MILON','PROVINS','COULOMMIERS'],
    term_1: ['MEAUX','CHÂTEAU','PROVINS','COULOMMIERS','FERTÉ'],
    mots_2: ['PARIS','EST'],
    term_2: ['PARIS','EST'],
  },
  R: {
    labels: ['⇩ SUD (Montereau / Montargis)', '⇧ PARIS GARE DE LYON'],
    mots_1: ['MONTEREAU','MONTARGIS','MELUN'],
    term_1: ['MONTEREAU','MONTARGIS'],
    mots_2: ['PARIS','LYON','BERCY'],
    term_2: ['PARIS','LYON'],
  },
  U: {
    labels: ['⇩ SUD (La Verrière)', '⇧ NORD (La Défense)'],
    mots_1: ['VERRIERE','VERRIÈRE','TRAPPES'],
    term_1: ['VERRIERE','VERRIÈRE'],
    mots_2: ['DEFENSE','DÉFENSE'],
    term_2: ['DEFENSE','DÉFENSE'],
  },
  V: {
    labels: ['⇦ OUEST (Versailles-Chantiers)', '⇨ EST (Massy-Palaiseau)'],
    mots_1: ['VERSAILLES','CHANTIERS'],
    term_1: ['VERSAILLES'],
    mots_2: ['MASSY','PALAISEAU'],
    term_2: ['MASSY'],
  },
};

// Routes ordonnées du terminus banlieue vers Paris.
// direction 0 (idxTerm < idxDep) = vers le terminus banlieue = p1 = labels[0]
// direction 1 (idxTerm > idxDep) = vers Paris           = p2 = labels[1]
export const TOPOLOGIE_LIGNES: Record<string, { routes: string[][] }> = {
  A: {
    // Ouest → Est : terminus ouest en premier, Paris au milieu, terminus est en dernier
    routes: [
      ['GERMAIN','PECQ','VESINET','CHATOU','RUEIL','NANTERRE','DEFENSE','GAULLE','AUBER','CHATELET','LYON','NATION','VINCENNES','FONTENAY-SOUS','NOGENT','JOINVILLE','MAUR','CHAMPIGNY','VARENNE','SUCY','BOISSY'],
      ['CERGY','NEUVILLE','CONFLANS','ACHERES','MAISONS','SARTROUVILLE','HOUILLES','NANTERRE','DEFENSE','GAULLE','AUBER','CHATELET','LYON','NATION','VINCENNES','VAL DE FONTENAY','NEUILLY','BRY','NOISY','LOGNES','TORCY','BUSSY','EUROPE','CHESSY'],
      ['POISSY','ACHERES','MAISONS','SARTROUVILLE','HOUILLES','NANTERRE','DEFENSE','GAULLE','AUBER','CHATELET','LYON','NATION','VINCENNES','VAL DE FONTENAY','NEUILLY','BRY','NOISY','LOGNES','TORCY','BUSSY','EUROPE','CHESSY'],
      ['CERGY','NEUVILLE','CONFLANS','ACHERES','MAISONS','SARTROUVILLE','HOUILLES','NANTERRE','DEFENSE','GAULLE','AUBER','CHATELET','LYON','NATION','VINCENNES','FONTENAY-SOUS','NOGENT','JOINVILLE','MAUR','CHAMPIGNY','VARENNE','SUCY','BOISSY'],
      ['GERMAIN','PECQ','VESINET','CHATOU','RUEIL','NANTERRE','DEFENSE','GAULLE','AUBER','CHATELET','LYON','NATION','VINCENNES','VAL DE FONTENAY','NEUILLY','BRY','NOISY','LOGNES','TORCY','BUSSY','EUROPE','CHESSY'],
    ],
  },
  B: {
    // Sud → Nord : terminus sud en premier, Paris au milieu, terminus nord en dernier
    routes: [
      ['REMY','COURCELLE','GIF','BURES','ORSAY','LOZERE','PALAISEAU','MASSY','VERRIERES','FONTAINE','CROIX','BOURG','BAGNEUX','ARCUEIL','LAPLACE','GENTILLY','CITE UNIVERSITAIRE','DENFERT','ROYAL','LUXEMBOURG','MICHEL','CHATELET','EST','NORD','PLAINE','COURNEUVE','BOURGET','DRANCY','BLANC','AULNAY','SEVRAN LIVRY','VERT GALANT','VILLEPARISIS','MITRY'],
      ['ROBINSON','FONTENAY','SCEAUX','BOURG','BAGNEUX','ARCUEIL','LAPLACE','GENTILLY','CITE UNIVERSITAIRE','DENFERT','ROYAL','LUXEMBOURG','MICHEL','CHATELET','EST','NORD','PLAINE','COURNEUVE','BOURGET','DRANCY','BLANC','AULNAY','SEVRAN BEAUDOTTES','VILLEPINTE','PARC','GAULLE'],
    ],
  },
  C: {
    // Ouest/Nord → Sud/Est : terminus ouest en premier
    routes: [
      ['PONTOISE','AUMONE','LIESSE','PIERRELAYE','MONTIGNY','FRANCONVILLE','CERNAY','ERMONT','GRATIEN','EPINAY SUR SEINE','GENNEVILLIERS','GRESILLONS','SAINT-OUEN','CLICHY','PEREIRE','MAILLOT','FOCH','HENRI MARTIN','BOULAINVILLIERS','KENNEDY','CHAMP DE MARS','ALMA','INVALIDES','ORSAY','MICHEL','AUSTERLITZ','BIBLIOTHEQUE','IVRY','VITRY','ARDOINES','CHOISY','SAULES','ORLY','RUNGIS','FRATERNELLE','CHEMIN D\'ANTONY','VERRIERES','MASSY PALAISEAU'],
      ['QUENTIN','CYR','VERSAILLES CHANTIERS','PORCHEFONTAINE','VIROFLAY','CHAVILLE','MEUDON','ISSY','VAL DE SEINE','GARIGLIANO','JAVEL','CHAMP DE MARS','ALMA','INVALIDES','ORSAY','MICHEL','AUSTERLITZ','BIBLIOTHEQUE','IVRY','VITRY','ARDOINES','CHOISY','VILLENEUVE LE ROI','ABLON','ATHIS','JUVISY','SAVIGNY','EPINAY SUR ORGE','GENEVIEVE','MICHEL SUR ORGE','BRETIGNY','MAROLLES','BOURAY','LARDY','CHAMARANDE','ETRECHY','ETAMPES'],
      ['VERSAILLES CHATEAU','PORCHEFONTAINE','VIROFLAY','CHAVILLE','MEUDON','ISSY','VAL DE SEINE','GARIGLIANO','JAVEL','CHAMP DE MARS','ALMA','INVALIDES','ORSAY','MICHEL','AUSTERLITZ','BIBLIOTHEQUE','IVRY','VITRY','ARDOINES','CHOISY','VILLENEUVE LE ROI','ABLON','ATHIS','JUVISY','SAVIGNY','EPINAY SUR ORGE','GENEVIEVE','MICHEL SUR ORGE','BRETIGNY','NORVILLE','ARPAJON','EGLY','BREUILLET','CHERON','SERMAISE','DOURDAN'],
      ['JUVISY','SAVIGNY','EPINAY SUR ORGE','GRAVIGNY','PETIT VAUX','MASSY PALAISEAU','IGNY','BIEVRES','VAUBOYEN','JOUY','PETIT JOUY','VERSAILLES CHANTIERS'],
    ],
  },
  D: {
    // Terminus sud/Melun en premier → Paris → terminus nord/Creil en dernier
    routes: [
      ['MELUN','MEE','CESSON','SAVIGNY LE TEMPLE','LIEUSAINT','COMBS','BOUSSY','BRUNOY','YERRES','MONTGERON','VILLENEUVE SAINT-GEORGES','TRIAGE','POMPADOUR','VERT DE MAISONS','ALFORTVILLE','MAISONS ALFORT','LYON','CHATELET','NORD','STADE DE FRANCE','DENIS','PIERREFITTE','GARGES','GONESSE','VILLIERS LE BEL','GOUSSAINVILLE','LOUVRES','SURVILLIERS','CHANTILLY','CREIL'],
      ['MALESHERBES','GIRONVILLE','BUNO','MAISSE','BOUTIGNY','FERTE ALAIS','BALLANCOURT','MENNECY','MOULIN GALANT','CORBEIL','BRAS DE FER','COURCOURONNES','ORANGIS BOIS','GRIGNY','VIRY','JUVISY','VIGNEUX','VILLENEUVE SAINT-GEORGES','TRIAGE','POMPADOUR','VERT DE MAISONS','ALFORTVILLE','MAISONS ALFORT','LYON','CHATELET','NORD','STADE DE FRANCE','DENIS','PIERREFITTE','GARGES','GONESSE','VILLIERS LE BEL','GOUSSAINVILLE','LOUVRES','SURVILLIERS','CHANTILLY','CREIL'],
      ['MELUN','VOSVES','PONTHIERRY','COUDRAY','PLESSIS CHENET','VILLABE','ESSONNES ROBINSON','CORBEIL','VAL DE SEINE','GRAND BOURG','RIS ORANGIS','VIRY','JUVISY','VIGNEUX','VILLENEUVE SAINT-GEORGES','TRIAGE','POMPADOUR','VERT DE MAISONS','ALFORTVILLE','MAISONS ALFORT','LYON','CHATELET','NORD','STADE DE FRANCE','DENIS','PIERREFITTE','GARGES','GONESSE','VILLIERS LE BEL','GOUSSAINVILLE','LOUVRES','SURVILLIERS','CHANTILLY','CREIL'],
    ],
  },
  E: {
    // Ouest → Est : terminus ouest en premier
    routes: [
      ['NANTERRE','DEFENSE','MAILLOT','HAUSSMANN','MAGENTA','ROSA PARKS','PANTIN','NOISY','BONDY','RAINCY','CHENAY','CHELLES'],
      ['NANTERRE','DEFENSE','MAILLOT','HAUSSMANN','MAGENTA','ROSA PARKS','PANTIN','NOISY','ROSNY BOIS PERRIER','ROSNY SOUS BOIS','VAL DE FONTENAY','NOGENT','BOULLEREAUX','VILLIERS','YVRIS','EMERAINVILLE','ROISSY','OZOIR','GRETZ','TOURNAN'],
    ],
  },
  H: {
    // Terminus nord en premier → Paris Nord en dernier
    routes: [
      ['PONTOISE','AUMONE','LIESSE','PIERRELAYE','MONTIGNY','FRANCONVILLE','CERNAY','ERMONT EAUBONNE','CHAMP DE COURSES','ENGHIEN','EPINAY','DENIS','NORD'],
      ['PERSAN','CHAMPAGNE','ISLE-ADAM','VALMONDOIS','MERIEL','MERY','FREPILLON','BESSANCOURT','TAVERNY','VAUCELLES','SAINT-PRIX','GROS NOYER','ERMONT HALTE','ERMONT EAUBONNE','CHAMP DE COURSES','ENGHIEN','EPINAY','DENIS','NORD'],
      ['CREIL','ESSERENT','PRECY','BORAN','BRUYERES','PERSAN','NOINTEL','PRESLES','MONTSOULT','BOUFFEMONT','DOMONT','ECOUEN','SARCELLES','GROSLAY','DEUIL','EPINAY','DENIS','NORD'],
      ['LUZARCHES','SEUGY','VIARMES','VILLAINES','MONTSOULT','BOUFFEMONT','DOMONT','ECOUEN','SARCELLES','GROSLAY','DEUIL','EPINAY','DENIS','NORD'],
    ],
  },
  J: {
    // Terminus ouest en premier → Paris St-Lazare en dernier
    routes: [
      ['ERMONT','SANNOIS','ARGENTEUIL','STADE','COLOMBES','BOIS COLOMBES','ASNIERES','LAZARE'],
      ['GISORS','CHARS','BOISSY L\'AILLERIE','OSNY','PONTOISE','AUMONE','ERAGNY','CONFLANS SAINTE-HONORINE','HERBLAY','FRETTE','CORMEILLES','VAL D\'ARGENTEUIL','ARGENTEUIL','LAZARE'],
      ['MANTES LA JOLIE','MANTES STATION','LIMAY','ISSOU','GARGENVILLE','JUZIERS','MEULAN','THUN','VAUX','TRIEL','CHANTELOUP','ANDRESY','MAURECOURT','FIN D\'OISE','CONFLANS SAINTE-HONORINE','HERBLAY','FRETTE','CORMEILLES','VAL D\'ARGENTEUIL','ARGENTEUIL','LAZARE'],
      ['VERNON','EVREUX','BUEIL','BREVAL','BONNIERES','ROSNY','MANTES LA JOLIE','MANTES STATION','EPONE','AUBERGENVILLE','MUREAUX','VERNOUILLET','VILLENNES','POISSY','MAISONS LAFFITTE','SARTROUVILLE','HOUILLES','LAZARE'],
    ],
  },
  K: {
    // Terminus nord en premier → Paris Nord en dernier
    routes: [['CREPY','ORMOY','NANTEUIL','PLESSIS','DAMMARTIN','THIEUX','COMPANS','MITRY','AULNAY','NORD']],
  },
  L: {
    // Terminus ouest en premier → Paris St-Lazare en dernier
    routes: [
      ['VERSAILLES RIVE DROITE','MONTREUIL','VIROFLAY RIVE DROITE','CHAVILLE RIVE DROITE','SEVRES','CLOUD','VAL D\'OR','SURESNES','PUTEAUX','DEFENSE','COURBEVOIE','BECON','ASNIERES','CLICHY','CARDINET','LAZARE'],
      ['NOM LA BRETECHE','ETANG','MARLY','LOUVECIENNES','BOUGIVAL','CELLE','VAUCRESSON','GARCHES','CLOUD','VAL D\'OR','SURESNES','PUTEAUX','DEFENSE','COURBEVOIE','BECON','ASNIERES','CLICHY','CARDINET','LAZARE'],
      ['CERGY LE HAUT','SAINT-CHRISTOPHE','CERGY PREFECTURE','NEUVILLE','FIN D\'OISE','ACHERES VILLE','MAISONS LAFFITTE','SARTROUVILLE','HOUILLES','NANTERRE UNIVERSITE','GARENNE','VALLEES','BECON','ASNIERES','CLICHY','CARDINET','LAZARE'],
    ],
  },
  N: {
    // Terminus ouest en premier → Paris Montparnasse en dernier
    routes: [
      ['DREUX','MARCHEZAIS','HOUDAN','TACOIGNIERES','ORGERUS','GARANCIERES','MONTFORT','VILLIERS','PLAISIR','VILLEPREUX','FONTENAY','CYR','VERSAILLES CHANTIERS','VIROFLAY RIVE GAUCHE','CHAVILLE RIVE GAUCHE','SEVRES RIVE GAUCHE','BELLEVUE','MEUDON','CLAMART','VANVES','MONTPARNASSE'],
      ['MANTES LA JOLIE','EPONE','NEZEL','MAULE','MAREIL','BEYNES','PLAISIR','VILLEPREUX','FONTENAY','CYR','VERSAILLES CHANTIERS','VIROFLAY RIVE GAUCHE','CHAVILLE RIVE GAUCHE','SEVRES RIVE GAUCHE','BELLEVUE','MEUDON','CLAMART','VANVES','MONTPARNASSE'],
      ['RAMBOUILLET','PERRAY','ESSARTS','COIGNIERES','VERRIERE','TRAPPES','QUENTIN','CYR','VERSAILLES CHANTIERS','VIROFLAY RIVE GAUCHE','CHAVILLE RIVE GAUCHE','SEVRES RIVE GAUCHE','BELLEVUE','MEUDON','CLAMART','VANVES','MONTPARNASSE'],
    ],
  },
  P: {
    // Terminus est en premier → Paris Est en dernier
    routes: [
      ['CHATEAU THIERRY','CHEZY','NOGENT L\'ARTAUD','NANTEUIL','FERTE SOUS JOUARRE','CHANGIS','TRILPORT','MEAUX','ESBLY','LAGNY','VAIRES','CHELLES','EST'],
      ['COULOMMIERS','MOUROUX','FAREMOUTIERS','GUERARD','MORTCERF','MARLES','TOURNAN','EST'],
      ['PROVINS','CHAMPBENOIST','SAINTE-COLOMBE','LONGUEVILLE','NANGIS','MORMANT','VERNEUIL','MORTCERF','MARLES','TOURNAN','EST'],
      ['FERTE MILON','MAREUIL','CROUY','LIZY','ISLES','TRILPORT','MEAUX'],
    ],
  },
  R: {
    // Terminus sud en premier → Paris Gare de Lyon en dernier
    routes: [
      ['MONTEREAU','SAINT-MAMMES','MORET','THOMERY','FONTAINEBLEAU','BOIS LE ROI','MELUN','LYON'],
      ['MONTARGIS','FERRIERES','DORDIVES','SOUPPES','BAGNEAUX','NEMOURS','BOURRON','MONTIGNY','MORET','THOMERY','FONTAINEBLEAU','BOIS LE ROI','MELUN','LYON'],
      ['MONTEREAU','PAROISSE','VERNOU','CHAMPAGNE','VULAINES','HERICY','FONTAINE LE PORT','CHARTRETTES','LIVRY','MELUN'],
    ],
  },
  U: {
    // Terminus sud (Verrière) en premier → La Défense en dernier
    routes: [['VERRIERE','TRAPPES','QUENTIN','CYR','VERSAILLES CHANTIERS','CHAVILLE','SEVRES','CLOUD','SURESNES','PUTEAUX','DEFENSE']],
  },
  V: {
    // Ouest → Est : Versailles en premier, Massy en dernier
    routes: [['VERSAILLES CHANTIERS','PETIT JOUY','JOUY','VAUBOYEN','BIEVRES','IGNY','MASSY PALAISEAU']],
  },
};
